[package]
name = "server_config"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"

[dependencies]
serde_yaml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
getset = "0.1.4"

